Build stages wiht new tenant url

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,12 +21,12 @@ notifications:
       - "Travis message: %{message}"
 stages:
   - shellcheck
-  # - tests
+  - tests
   - build
-  # - e2e-helm-deployment-test
-  # - e2e-cloud-function-deployment-test
+  - e2e-helm-deployment-test
+  - e2e-cloud-function-deployment-test
   - github-deploy
-  # - docker-deploy
+  - docker-deploy
   - gcp-install-release
 env:
   global:
@@ -37,47 +37,47 @@ env:
   - GCR_NAME="gcr.io/${GCP_PROJECT_ID}/dynatrace-gcp-monitor"
 jobs:
   include:
-  - stage: shellcheck
-    name: CheckStyle
-    language: minimal
-    script: |
-      status=0
-      for script in $(find . -iname "*.sh"); 
-      do
-        echo "Checking $script";
-        shellcheck -x "$script";
-        if [ $? -ne 0 ]; then
-          echo "ERROR: shellcheck failed at $script";
-          status=1;
-        fi;
-      done;
-      exit $status
-  - stage: tests
-    name: Tests
-    language: python
-    python:
-      - "3.8"
-    env:
-      - PYTHONPATH="$TRAVIS_BUILD_DIR/src:$TRAVIS_BUILD_DIR/tests"
-    addons:
-      apt:
-        packages:
-          - default-jre
-    cache:
-      directories:
-        - "$HOME/.cache/pip"
-        - "$HOME/.wgetcache"
-    install:
-      - pip install -r src/requirements.txt
-      - pip install -r tests/requirements.txt
-    script:
-      - pytest tests/unit -v
-      - pytest tests/integration/logs -v
+  # - stage: shellcheck
+  #   name: CheckStyle
+  #   language: minimal
+  #   script: |
+  #     status=0
+  #     for script in $(find . -iname "*.sh"); 
+  #     do
+  #       echo "Checking $script";
+  #       shellcheck -x "$script";
+  #       if [ $? -ne 0 ]; then
+  #         echo "ERROR: shellcheck failed at $script";
+  #         status=1;
+  #       fi;
+  #     done;
+  #     exit $status
+  # - stage: tests
+  #   name: Tests
+  #   language: python
+  #   python:
+  #     - "3.8"
+  #   env:
+  #     - PYTHONPATH="$TRAVIS_BUILD_DIR/src:$TRAVIS_BUILD_DIR/tests"
+  #   addons:
+  #     apt:
+  #       packages:
+  #         - default-jre
+  #   cache:
+  #     directories:
+  #       - "$HOME/.cache/pip"
+  #       - "$HOME/.wgetcache"
+  #   install:
+  #     - pip install -r src/requirements.txt
+  #     - pip install -r tests/requirements.txt
+  #   script:
+  #     - pytest tests/unit -v
+  #     - pytest tests/integration/logs -v
 #       The cd is executed due to the fact that the wiremock instance initialized in the test is using
 #       the mappings (folder mappings) and the files ( __files) in the current execution dir.
-      - |
-          cd tests/integration/metrics
-          pytest -v
+      # - |
+      #     cd tests/integration/metrics
+      #     pytest -v
 
   - stage: build
     name: Build
@@ -109,14 +109,14 @@ jobs:
       - ./build/function-package.sh
       - gsutil -m cp ./artefacts/* gs://travis-e2e/commit-${TRAVIS_COMMIT}_build-${TRAVIS_BUILD_ID}/
 
-  - stage: docker-deploy
-    name: Docker Hub deploy
-    if: tag =~ /^release-.*
-    language: minimal
-    script:
-      - ./build/version.sh
-      - ./build/docker-deploy.sh
-    env: PUSH=true
+  # - stage: docker-deploy
+  #   name: Docker Hub deploy
+  #   if: tag =~ /^release-.*
+  #   language: minimal
+  #   script:
+  #     - ./build/version.sh
+  #     - ./build/docker-deploy.sh
+  #   env: PUSH=true
 
   - stage: github-deploy
     name: GitHub deploy
@@ -174,93 +174,93 @@ jobs:
     script:
       - ./scripts/perform-deployment-function.sh
 
-  - stage: e2e-helm-deployment-test
-    name: E2E GCP helm deployment test
-    sudo: required
-    language: python
-    python:
-      - "3.8"
-    cache:
-      directories:
-        - "$HOME/.wgetcache"
-        - "$HOME/google-cloud-sdk/"
-        - "$HOME/.cache/pip"
-    env:
-      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
-      - PUBSUB_TOPIC="e2e_test_topic_${TRAVIS_BUILD_ID}"
-      - PUBSUB_SUBSCRIPTION="e2e_test_subscription_${TRAVIS_BUILD_ID}"
-      - IAM_SERVICE_ACCOUNT="e2e-test-sa-${TRAVIS_BUILD_ID}"
-      - LOG_ROUTER="e2e_test_log_router_${TRAVIS_BUILD_ID}"
-      - IAM_ROLE_PREFIX="e2e_test_${TRAVIS_BUILD_ID}"
-      - K8S_CLUSTER="e2e-test-master"
-      - E2E=true
-      - CLOUD_FUNCTION_NAME="e2e_test_sample_app"
-      - GCP_PROJECT_2_ID="dynatrace-gcp-extension-2"
-      - CLOUD_RUN_REVISION_NAME="e2e-test-sample-service-00002-bif"
-      - secure: "muHGNxIK6fxTltIsGgms6v3dleuQ1LZyQmZIGQDSfQ5sfYDYEvR2xsabK237AipSSGppoVhc7S6ri8A/WNQautHUfdBOsVn1i7czzoPhELdOJkAiigXrI3kla68OTCiC0TPwWbIYOxzmiYDHZr+rYbA1773O0iyhWHiTVQerLMndn0wCFWUUnLbD1WfzdAxlfSo1rd7u81m8g4efLIUppo/fjfaxmVwvo1oIfensGVknyOE+gtSh/OpGdYfNeOqxoDGOoMe5bnCqibUoREXRzUZKGb6upxMMmW6E3hGG02kqle4jYjaC7Uiu2IVZsK38iAWNGwIRy21CIXNHn4R6we44n5JLH92aiRtVw8D/fDOnN2gWTtmdrvoB8YklbaYZBnDrGJxI6rESfeQjwD8ImWWKUJFUlwovKjNWhOw8RMhPVtPOuC00+F2UDq5NosrWYGUjLjaKFC/4nysOiK2DgsMBF/Mk1Ei1BDMYmcHQ7Jsrs8ys/kgPasV3Qs9xOuSJpF+AiwKPfI1R9bxYiORg70TNz62wPD7FlKWIVe0DvhrWcHCTpnrROabt6B0hUROfljCZe2H+j8HD9uCJCJHk5qP7llNVofVnz8w+s90wLEKpUNn2rVUH0fzffYM7YaLRPhzLEUJSQso3a7hXFfcoUow8OOPTmCgViGCfPjuy2zc="
-      - secure: "pmnIVxqixHvgidZRXXmWKUfuyAeBun1eOzhP79onCFTazGRnMG+Lv+c4422nHUDA9KsmYPezjk3ESfd8EGlfL0ZFQbL45eQp3oGcbN9to6wDj8g6xyrr+tG9GJ4jirO5DlLZ5I0y3WywmE+anzbFdjV0+sWTe1QWxtzqbySCwewPThBvn/iOdJMaPh7S328W7WxkD095ZCC2pQx42Mwfforw+1Jg6yd2ZI3W4b0+KsrTBveeyfj0A7F3e7uTrA+zXst26sYY37zlT/IYT5hgpQiGqbWpnoTrYLvgjdnLxSz43zWKY/YDxFU7DY1t0HIKC4N9vWynjcx1R8VjWT4SCy5f1TPHNvNt5zJUBJ59zUBuTL8Yi6FfMqDqHRLq6W8/bMJe0QSrjJFocWIs+YD+AlCbTS6rhpynzsrbS/GHo6KjVkFhXIRVjp798IFLHsJQ2JonO8McWdaldQszu8O/rB1v8B9tXsUoc5e0pJFSXI9qVwPYAAMOx1bmDPOBQoapx5ciwUh0U2rPZyGDQVh+iDcGlGX1ttWlF83vaRYbzBYqzLzcckNSnHlva6F/ZwcTQsbrZSM5Trz3OUk7fWJMRuf7XjKFAEWzASFLYpdZ1EVP+vUmxpT8OzA9kUn3XMFd9sTm9v5GZ0zQscM+/WSmJsPPGwlQZRX5CtHbq7mySJ0="
-      - DYNATRACE_URL=${DYNATRACE_URL}
-      - DYNATRACE_ACCESS_KEY=${DYNATRACE_ACCESS_KEY}
-    install:
-      # Install GCP SDK if not already cached
-      - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
-      - source $HOME/google-cloud-sdk/path.bash.inc
-      - gcloud version
-      - pip install -r tests/requirements.txt
-      - ./tests/e2e/helm-preinstall.sh
-    before_script:
-      - openssl aes-256-cbc -K $encrypted_1019fd6574a7_key -iv $encrypted_1019fd6574a7_iv -in tests/e2e/e2e-gcp-sa-key.json.enc -out tests/e2e/e2e-gcp-sa-key.json -d
-      - gcloud auth activate-service-account --key-file tests/e2e/e2e-gcp-sa-key.json
-      - ./build/get_ext_tools.sh
-      - ./tests/e2e/deployment-test-cleanup.sh
-      - ./tests/e2e/before-deployment-test-helm-cleanup.sh
-      - ./tests/e2e/before-deployment-test-extensions-cleanup.sh
-      - gcloud components install gke-gcloud-auth-plugin; export USE_GKE_GCLOUD_AUTH_PLUGIN=True; gcloud components update;
-    script:
-      - mkdir -p ./artefacts/ && gsutil cp gs://travis-e2e/commit-${TRAVIS_COMMIT}_build-${TRAVIS_BUILD_ID}/helm-deployment-package.tar ./artefacts/
-      - travis_wait 60 ./tests/e2e/execute-tests.sh
-    after_script:
-      - ./tests/e2e/deployment-test-cleanup.sh
+  # - stage: e2e-helm-deployment-test
+  #   name: E2E GCP helm deployment test
+  #   sudo: required
+  #   language: python
+  #   python:
+  #     - "3.8"
+  #   cache:
+  #     directories:
+  #       - "$HOME/.wgetcache"
+  #       - "$HOME/google-cloud-sdk/"
+  #       - "$HOME/.cache/pip"
+  #   env:
+  #     - CLOUDSDK_CORE_DISABLE_PROMPTS=1
+  #     - PUBSUB_TOPIC="e2e_test_topic_${TRAVIS_BUILD_ID}"
+  #     - PUBSUB_SUBSCRIPTION="e2e_test_subscription_${TRAVIS_BUILD_ID}"
+  #     - IAM_SERVICE_ACCOUNT="e2e-test-sa-${TRAVIS_BUILD_ID}"
+  #     - LOG_ROUTER="e2e_test_log_router_${TRAVIS_BUILD_ID}"
+  #     - IAM_ROLE_PREFIX="e2e_test_${TRAVIS_BUILD_ID}"
+  #     - K8S_CLUSTER="e2e-test-master"
+  #     - E2E=true
+  #     - CLOUD_FUNCTION_NAME="e2e_test_sample_app"
+  #     - GCP_PROJECT_2_ID="dynatrace-gcp-extension-2"
+  #     - CLOUD_RUN_REVISION_NAME="e2e-test-sample-service-00002-bif"
+  #     - secure: "muHGNxIK6fxTltIsGgms6v3dleuQ1LZyQmZIGQDSfQ5sfYDYEvR2xsabK237AipSSGppoVhc7S6ri8A/WNQautHUfdBOsVn1i7czzoPhELdOJkAiigXrI3kla68OTCiC0TPwWbIYOxzmiYDHZr+rYbA1773O0iyhWHiTVQerLMndn0wCFWUUnLbD1WfzdAxlfSo1rd7u81m8g4efLIUppo/fjfaxmVwvo1oIfensGVknyOE+gtSh/OpGdYfNeOqxoDGOoMe5bnCqibUoREXRzUZKGb6upxMMmW6E3hGG02kqle4jYjaC7Uiu2IVZsK38iAWNGwIRy21CIXNHn4R6we44n5JLH92aiRtVw8D/fDOnN2gWTtmdrvoB8YklbaYZBnDrGJxI6rESfeQjwD8ImWWKUJFUlwovKjNWhOw8RMhPVtPOuC00+F2UDq5NosrWYGUjLjaKFC/4nysOiK2DgsMBF/Mk1Ei1BDMYmcHQ7Jsrs8ys/kgPasV3Qs9xOuSJpF+AiwKPfI1R9bxYiORg70TNz62wPD7FlKWIVe0DvhrWcHCTpnrROabt6B0hUROfljCZe2H+j8HD9uCJCJHk5qP7llNVofVnz8w+s90wLEKpUNn2rVUH0fzffYM7YaLRPhzLEUJSQso3a7hXFfcoUow8OOPTmCgViGCfPjuy2zc="
+  #     - secure: "pmnIVxqixHvgidZRXXmWKUfuyAeBun1eOzhP79onCFTazGRnMG+Lv+c4422nHUDA9KsmYPezjk3ESfd8EGlfL0ZFQbL45eQp3oGcbN9to6wDj8g6xyrr+tG9GJ4jirO5DlLZ5I0y3WywmE+anzbFdjV0+sWTe1QWxtzqbySCwewPThBvn/iOdJMaPh7S328W7WxkD095ZCC2pQx42Mwfforw+1Jg6yd2ZI3W4b0+KsrTBveeyfj0A7F3e7uTrA+zXst26sYY37zlT/IYT5hgpQiGqbWpnoTrYLvgjdnLxSz43zWKY/YDxFU7DY1t0HIKC4N9vWynjcx1R8VjWT4SCy5f1TPHNvNt5zJUBJ59zUBuTL8Yi6FfMqDqHRLq6W8/bMJe0QSrjJFocWIs+YD+AlCbTS6rhpynzsrbS/GHo6KjVkFhXIRVjp798IFLHsJQ2JonO8McWdaldQszu8O/rB1v8B9tXsUoc5e0pJFSXI9qVwPYAAMOx1bmDPOBQoapx5ciwUh0U2rPZyGDQVh+iDcGlGX1ttWlF83vaRYbzBYqzLzcckNSnHlva6F/ZwcTQsbrZSM5Trz3OUk7fWJMRuf7XjKFAEWzASFLYpdZ1EVP+vUmxpT8OzA9kUn3XMFd9sTm9v5GZ0zQscM+/WSmJsPPGwlQZRX5CtHbq7mySJ0="
+  #     - DYNATRACE_URL=${DYNATRACE_URL}
+  #     - DYNATRACE_ACCESS_KEY=${DYNATRACE_ACCESS_KEY}
+  #   install:
+  #     # Install GCP SDK if not already cached
+  #     - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
+  #     - source $HOME/google-cloud-sdk/path.bash.inc
+  #     - gcloud version
+  #     - pip install -r tests/requirements.txt
+  #     - ./tests/e2e/helm-preinstall.sh
+  #   before_script:
+  #     - openssl aes-256-cbc -K $encrypted_1019fd6574a7_key -iv $encrypted_1019fd6574a7_iv -in tests/e2e/e2e-gcp-sa-key.json.enc -out tests/e2e/e2e-gcp-sa-key.json -d
+  #     - gcloud auth activate-service-account --key-file tests/e2e/e2e-gcp-sa-key.json
+  #     - ./build/get_ext_tools.sh
+  #     - ./tests/e2e/deployment-test-cleanup.sh
+  #     - ./tests/e2e/before-deployment-test-helm-cleanup.sh
+  #     - ./tests/e2e/before-deployment-test-extensions-cleanup.sh
+  #     - gcloud components install gke-gcloud-auth-plugin; export USE_GKE_GCLOUD_AUTH_PLUGIN=True; gcloud components update;
+  #   script:
+  #     - mkdir -p ./artefacts/ && gsutil cp gs://travis-e2e/commit-${TRAVIS_COMMIT}_build-${TRAVIS_BUILD_ID}/helm-deployment-package.tar ./artefacts/
+  #     - travis_wait 60 ./tests/e2e/execute-tests.sh
+  #   after_script:
+  #     - ./tests/e2e/deployment-test-cleanup.sh
 
-  - stage: e2e-cloud-function-deployment-test
-    name: E2E GCP Cloud Function deployment test
-    sudo: required
-    language: python
-    python:
-      - "3.8"
-    cache:
-      directories:
-        - "$HOME/.wgetcache"
-        - "$HOME/google-cloud-sdk/"
-        - "$HOME/.cache/pip"
-    env:
-      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
-      - E2E=true
-      - DYNATRACE_URL_SECRET_NAME="DYNATRACE_URL_${TRAVIS_BUILD_ID}"
-      - DYNATRACE_ACCESS_KEY_SECRET_NAME="DYNATRACE_ACCESS_KEY_${TRAVIS_BUILD_ID}"
-      - IAM_SERVICE_ACCOUNT="e2e-test-sa-${TRAVIS_BUILD_ID}"
-      - IAM_ROLE_METRCICS="e2e_test_cloud_function_${TRAVIS_BUILD_ID}.metrics"
-      - PUBSUB_TOPIC="e2e_test_topic_${TRAVIS_BUILD_ID}"
-      - CLOUD_SCHEDULER="e2e_test_scheduler_${TRAVIS_BUILD_ID}"
-      - METRIC_FORWARDING_FUNCTION="e2e_test_function_${TRAVIS_BUILD_ID}"
-      - CLOUD_FUNCTION_NAME="e2e_test_sample_app"
-      - GCP_PROJECT_2_ID="dynatrace-gcp-extension-2"
-      - CLOUD_RUN_REVISION_NAME="e2e-test-sample-service-00002-bif"
-      - DYNATRACE_URL=${DYNATRACE_URL}
-      - DYNATRACE_ACCESS_KEY=${DYNATRACE_ACCESS_KEY}
-    install:
-      # Install GCP SDK if not already cached
-      - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
-      - source $HOME/google-cloud-sdk/path.bash.inc
-      - gcloud version
-      - pip install -r tests/requirements.txt
-    before_script:
-      - openssl aes-256-cbc -K $encrypted_1019fd6574a7_key -iv $encrypted_1019fd6574a7_iv -in tests/e2e/e2e-gcp-sa-key.json.enc -out tests/e2e/e2e-gcp-sa-key.json -d
-      - gcloud auth activate-service-account --key-file tests/e2e/e2e-gcp-sa-key.json
-      - ./build/get_ext_tools.sh
-      - ./tests/e2e/before-deployment-test-extensions-cleanup.sh
-    script:
-      - mkdir -p ./artefacts/ && gsutil -m cp gs://travis-e2e/commit-${TRAVIS_COMMIT}_build-${TRAVIS_BUILD_ID}/* ./artefacts/
-      - travis_wait 60 ./tests/e2e/execute-tests-cloud-function.sh
-    after_script:
-      - ./tests/e2e/deployment-test-cleanup-cloud-function.sh
+  # - stage: e2e-cloud-function-deployment-test
+  #   name: E2E GCP Cloud Function deployment test
+  #   sudo: required
+  #   language: python
+  #   python:
+  #     - "3.8"
+  #   cache:
+  #     directories:
+  #       - "$HOME/.wgetcache"
+  #       - "$HOME/google-cloud-sdk/"
+  #       - "$HOME/.cache/pip"
+  #   env:
+  #     - CLOUDSDK_CORE_DISABLE_PROMPTS=1
+  #     - E2E=true
+  #     - DYNATRACE_URL_SECRET_NAME="DYNATRACE_URL_${TRAVIS_BUILD_ID}"
+  #     - DYNATRACE_ACCESS_KEY_SECRET_NAME="DYNATRACE_ACCESS_KEY_${TRAVIS_BUILD_ID}"
+  #     - IAM_SERVICE_ACCOUNT="e2e-test-sa-${TRAVIS_BUILD_ID}"
+  #     - IAM_ROLE_METRCICS="e2e_test_cloud_function_${TRAVIS_BUILD_ID}.metrics"
+  #     - PUBSUB_TOPIC="e2e_test_topic_${TRAVIS_BUILD_ID}"
+  #     - CLOUD_SCHEDULER="e2e_test_scheduler_${TRAVIS_BUILD_ID}"
+  #     - METRIC_FORWARDING_FUNCTION="e2e_test_function_${TRAVIS_BUILD_ID}"
+  #     - CLOUD_FUNCTION_NAME="e2e_test_sample_app"
+  #     - GCP_PROJECT_2_ID="dynatrace-gcp-extension-2"
+  #     - CLOUD_RUN_REVISION_NAME="e2e-test-sample-service-00002-bif"
+  #     - DYNATRACE_URL=${DYNATRACE_URL}
+  #     - DYNATRACE_ACCESS_KEY=${DYNATRACE_ACCESS_KEY}
+  #   install:
+  #     # Install GCP SDK if not already cached
+  #     - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
+  #     - source $HOME/google-cloud-sdk/path.bash.inc
+  #     - gcloud version
+  #     - pip install -r tests/requirements.txt
+  #   before_script:
+  #     - openssl aes-256-cbc -K $encrypted_1019fd6574a7_key -iv $encrypted_1019fd6574a7_iv -in tests/e2e/e2e-gcp-sa-key.json.enc -out tests/e2e/e2e-gcp-sa-key.json -d
+  #     - gcloud auth activate-service-account --key-file tests/e2e/e2e-gcp-sa-key.json
+  #     - ./build/get_ext_tools.sh
+  #     - ./tests/e2e/before-deployment-test-extensions-cleanup.sh
+  #   script:
+  #     - mkdir -p ./artefacts/ && gsutil -m cp gs://travis-e2e/commit-${TRAVIS_COMMIT}_build-${TRAVIS_BUILD_ID}/* ./artefacts/
+  #     - travis_wait 60 ./tests/e2e/execute-tests-cloud-function.sh
+  #   after_script:
+  #     - ./tests/e2e/deployment-test-cleanup-cloud-function.sh
